### ISSUE TITLE
Error with memory pool.

### ISSUE THREAD

**Issue by kfattila** [UWPR/Comet#14]
Hi Jimmy,

I am trying to create an indexed dataset with the -i option.  Comet runs smoothly when I issue the command:
```../comet/comet.exe -Phumvar.comet.params /home/data/mass_spec_data/Linfeng_012511_HapMap39_3.mzML```
So, the data and the fasta files exist.

However, Comet fails if I use the ```-i``` parameter:
```
 ../comet/comet.exe -i -Phumvar.comet.params /home/data/mass_spec_data/Linfeng_012511_HapMap39_3.mzML
 Comet version "2021.02 rev. 0"

 Creating peptide index file: Error with memory pool.
```
The error message appears immediately after issuing the command, within milliseconds. 

Could you please help me with how to run Comet with the -i option.

I'd greatly appreciate it!
Attila

**Comment by jke000** [comment]
Attila,

The proper command is either "comet.exe -i" or "comet.exe -i -P<alt.params>".  There's no need to specify a spectral file when indexing but if you do, it should just be ignored.

I sadly can't replicate the error you're seeing. I've tested indexing on four linux flavors (CentOS 7.9, Fedora 34, Ubuntu 18.04, Debian 10.5) as well as under Windows and they all run fine for me.  Any chance you can send me the humvar.comet.params file as well as the FASTA database specified in it?  A download link emailed me directly (engj at uw.edu) would be great.  Also, can you confirm whether or not you get the same error if you use the binary downloaded from our tagged release linux binary?  Just trying to narrow down the variables here that could be causing the issue you're seeing.

Jimmy

**Comment by kfattila** [comment]
Hi Jimmy, 

I greatly appreciate your prompt and useful response. I played around with comet a little bit, and it looks like I found the problem. The issue arises only when I specify the parameter ```num_threads = 1```. The ```comet.exe  -i``` works well with ```num_threads = 0```, ```num_threads = 2```, ```num_threads = 4```, I did not try other parameter values.

I observed the same results with:
1. my complied comet on Linux (I downloaded the source code and I compiled it on my Linux server) and 
2. I downloaded the binary ```comet.linux.exe``` from GitHub as you suggested, and it produces the same error message. 

For now I can create indexed DB with comet -i. 
Thanks again for your help.
Attila

**Comment by jke000** [comment]
Attila, thanks for identifying the parameter setting that invokes this bug. The ThreadPool code was rewritten as part of the 2021.01.0 release and this esoteric behavior is likely associated with that.  It will be addressed in the next release.

**Comment by kfattila** [comment]
Thank you!

**Comment by jke000** [comment]
Revert temp workaround and address this issue with commit [d6d193d](https://github.com/UWPR/Comet/commit/d6d193d4ba0d0a396da01908f292006b0ff286a8).
