### ISSUE TITLE
Thermo Raw file format not supported？

### ISSUE THREAD

**Issue by gudeqing** [UWPR/Comet#17]
![image](https://user-images.githubusercontent.com/30919159/156008766-2321ac48-6139-42bd-af07-bf13956e033b.png)

**Comment by jke000** [comment]
Thermo raw file support is only available with Comet's Windows binaries.  You will also need to install Thermo's freely available MSFileReader software on that Windows computer to support raw file access.  I will create a "[Notes](https://uwpr.github.io/Comet/notes/)" page on the Comet GitHub web site documenting this information.  You can obtain MSFileReader by first [registering for an account here](https://thermo.flexnetoperations.com/control/thmo/login) and then [going to this link to download that software](https://thermo.flexnetoperations.com/control/thmo/download?element=8554997).  Alternatively, you could convert that raw file to mzML/mzXML using [msconvert under Docker](https://hub.docker.com/r/chambm/pwiz-skyline-i-agree-to-the-vendor-licenses) on your linux system.
