### ISSUE TITLE
how to interpret and filter the quick search results?

### ISSUE THREAD

**Issue by gudeqing** [UWPR/Comet#18]
Hi,
First, thank you for sharing this easy-to-use tool.  I am quite new to do such kinds of MS/MS database searching. Now, I have the results generated by using RawTools (convert RAW file to mgf format) and Comet.  However, I do not know how to interpret and filter the results.  Following is my working pipeline（actually, I am not sure if  I am on the right way to do this kind of research):
1.  create fasta database with target peptides( length range from 8 to 11, generated by cutting predicted proteins into small segments, and predicted to be potential Neo-Antigen). I hope this is a reasonable way to build a target database, if not, please be kind to remind me of this. 
2.  search target peptides with mgf file as input using cosmet.linux.exe,  output txt file

my confusion:
1. how to interpret and filter the results. ( maybe by e-value or sp_score?) 
2. how can I judge if my predicted epitope sequence is truly detected by MS.

by the way, I could not find the realtimesearch.exe in the release page, did I missed something?

Best regards!

**Comment by jke000** [comment]
GitHub Issues this repository isn't the right mechanism to address the questions you're asking regarding how to analyze and interpret data.  Even the question about real time search support in Comet (what that entails and what the example code is meant to demonstrate) makes more sense to address on Comet's support group.  So please post these questions to the [Comet Google group](https://groups.google.com/g/comet-ms) and I'll respond there.  Or even feel free to email me directly at engj[at]uw.edu or jke000[at]gmail.com if you prefer.  I'm going to close this issue and look forward to interacting with you via the Google group or directly by email.
