### ISSUE TITLE
establish action'd builds

### ISSUE THREAD

**Issue by mammmals** [UWPR/Comet#2]
Add workflows to allow automatic building of `.exe` files for releases/tags.

**Comment by wfondrie** [comment]
Would you like some help tackling this?

**Comment by mammmals** [comment]
Sure! I was thinking of basing the workflow changes on these: https://github.com/gygilab/Monocle/tree/master/.github/workflows

**Comment by wfondrie** [comment]
Cool that sounds good. It looks like we might be able to simplify them even more too.

Here's what I would propose as for when the actions run:
- When a PR or commit is made to master trigger builds to make sure they work. If there are existing tests, we could run those too!
- When a new release is made, trigger a build and automatically upload the artifacts to the release.

**Comment by mammmals** [comment]
Sounds good @wfondrie , there's a branch (`issue-2`) for getting things going. I can load the initial dir and ymls, or do you want to get things started?

**Comment by wfondrie** [comment]
Cool - I'll use that branch. No need to worry about copying over the ymls.

**Comment by wfondrie** [comment]
I've opened a draft PR with working builds for Linux and MacOS.

The problem with the Windows build is just how to handle installing MSFileReader. Any ideas @mammmals?

**Comment by mammmals** [comment]
Very cool! Hmm, not sure the best way to do this, but will look into it. Any ideas @jke000 ?

**Comment by jke000** [comment]
Three's no way around having the required DLLs installed for the Windows build. Are we able to run commands like "regsvr32" as part of the windows-build?  If so, we can figure out if we can include the three required DLLs in the repository and issue the regsvr32 command before msbuild.

**Comment by wfondrie** [comment]
>Are we able to run commands like "regsvr32" as part of the windows-build? 

Yes, that shouldn't be a problem - GitHub Actions runs Windows as a VM with full admin privileges. 

Will we run into any licensing issues including the Thermo DLLs in the repo?

**Comment by jke000** [comment]
I'll inquire with Thermo about the DLLs; they're collaborators and use this project for their RTS application so there may be a tiny sliver of hope. If not, we can brainstorm about ways of pulling in those DLLs on demand from an external source for each build.

**Comment by wfondrie** [comment]
Another solution would be if they could create a Docker image with MSFileReader on Docker Hub or elsewhere. This would both solve our problem and likely help other developers as well.

**Comment by mammmals** [comment]
I took a look at the current MSFileReader license and I think it may be OK to distribute with some caveats. Getting clarification on this now.

**Comment by mammmals** [comment]
Following up: emails sent to try to get licensing for the VMs. Folks would still need to get the COM objects on their own machines to run the raw file reading (I believe).

**Comment by jke000** [comment]
Yes. This is would be just for us to be able to compile the Windows
binary.  To search with a Thermo raw file as input, users would need to
have MSFileReader installed themselves.

**Comment by jke000** [comment]
I just chatted with UW folks at the MacCoss/Noble bi-monthly
proteomics analysis meeting. Docker images, GiHub actions, etc. came up in
the discussion so I asked about the ability to include the vendor libraries
(or the 3 DLLs in our case) in an open source repository. Via the work
they've done with Skyline, they have vendor agreements to allow UW to
redistribute their libraries and the Comet project falls under that
umbrella.  So we're pretty safe include the 3 required vendor DLLs in our
repository for building Comet.  We just need to put them in a password
protected container (e.g. zip file) with the password of something like
"iagreetothevendorlicense" along with a corresponding readme describing the
vendor license.  I'll take care of that bit; this should solve our Windows
build.  Will's name came up with respect to Crux Docker images so expect a
follow-up from Bill soon on that.

**Comment by wfondrie** [comment]
Awesome! I have a crux GH Actions workflow that's hasn't been pushed to their repo, because of issues like this. Sounds like I can add that now too.

**Comment by mammmals** [comment]
Yeah, that's great! I haven't heard back from Thermo, but either way sounds like Comet's in good shape for shared builds.

**Comment by mammmals** [comment]
hey @wfondrie, looks like everything is building, but the release upload fails so nothing is heading up (assets, names, etc.).

**Comment by wfondrie** [comment]
Do we want an automatic new release with every merge into `master`?

I currently have it set up to trigger release uploads when a new GitHub release is created manually, under the [Releases](https://github.com/UWPR/Comet/releases) tab.

**Comment by mammmals** [comment]
Yeah, just saw that and triggered a pre-release test! Fingers crossed. 
We had been talking about merge releases, but this should work just as well.

**Comment by mammmals** [comment]
I would call this a resounding success and will close the issue for now!
