### ISSUE TITLE
No retention time in mzid output

### ISSUE THREAD

**Issue by MKoesters** [UWPR/Comet#20]
Hi,

Thanks for putting this awesome tool on github!

After trying comet, we are convinced that we want to use your tool for our pipeline, however we realised there is no retention time in the mzid output file.
Would it be possible to add this as in e.g. msgfplus mzid output?

Best,
Manuel

**Comment by jke000** [comment]
Manuel,

I'm sorry but I only became aware of this issue today.  I just wanted to note that I went ahead and added retention times to the mzid output with commit [7298005](https://github.com/UWPR/Comet/commit/729800599f9bc111fb16587ba86e2d97bb34bc0b). If you're interested in testing this for me before it makes it into the next official release, feel free to message me directly and I'll send you a binary if needed.

Jimmy
