### ISSUE TITLE
Problems in exported mzid files

### ISSUE THREAD

**Issue by julianu** [UWPR/Comet#21]
I just stumbled across some problems regarding exported mzid files in version 2022.01 rev. 0 while trying to parse the files with jMzIdentML. I still did not get the parsing done, but here are some general problems with the exports right now:

1) If for some reason the `&` symbol ends up in the id of an XML tag (e.g. from a protein accession or description), it is not escaped to `&amp;`" and thus breaks XML validity
2) The `<SpectraData>` in `<Inputs>` gets the id "SD_1", while in `<AnalysisCollection> -> <SpectrumIdentification>` it is referenced by "SD1"
3)  The actual `<SpectrumIdentificationList>` in `<AnalysisData>` has the id "SIL_1", while its reference at other places is "SIL"
4) Directly after the `<DataCollection>` is always a `"`

Best,
Julian

**Comment by jke000** [comment]
mzid files now validate and can be parsed into limelight
