### ISSUE TITLE
How to cite?

### ISSUE THREAD

**Issue by moranegg** [UWPR/Comet#22]
Hello,

I would like to cite this software for an article about FAIR software. Do you have a citation preference?
I can reference the code with a Software Heritage IDentifier (SWHID):
https://archive.softwareheritage.org/swh:1:dir:1da1428095251eb650036297e61601723f2b4742;origin=https://github.com/puregome/notebooks;visit=swh:1:snp:491ecb53ec5aae6e8faba8b7587f8d19ce857c73;anchor=swh:1:rev:a31d8061a7f82fb811e946efbe86ad205163270b
But I'm missing the credit info and title for the citation.

Thank you for your help.

Best,
Morane

**Comment by jke000** [comment]
The preferred citation for this software is https://analyticalsciencejournals.onlinelibrary.wiley.com/doi/abs/10.1002/pmic.201200439.
