### ISSUE TITLE
Give user warning about spectrum_batch_size

### ISSUE THREAD

**Issue by wsnoble** [UWPR/Comet#27]
I had a comet job run out of memory, and it took me a while to remember/figure out to set the `spectrum_batch_size`. I think it would be good if, when the `spectrum_batch_size` is 0, you print a message to stderr that says something like this:

```
Reading all spectra into memory.
If your search terminates at this point, please set the spectrum_batch_size parameter.
```

Without this message, I was just seeing the job stop with no explanation.

**Comment by jke000** [comment]
Incorporated warning message in release 2022.01.2 via commit [21f2509](https://github.com/UWPR/Comet/commit/21f2509eab68d6dbeacd89dd28acb26bbb5b89ba).
