### ISSUE TITLE
Broken link in documentation

### ISSUE THREAD

**Issue by jspaezp** [UWPR/Comet#28]
Hello!

I noticed that the link to percolator in the documentation is broken.

https://comet-ms.sourceforge.net/parameters/parameters_202101/output_percolatorfile.php

"Controls whether to output search results in a [Percolator's](http://per-colator.com/) tab-delimited input format."

Thank you very much for the amazing search engine!
Best!

**Comment by jke000** [comment]
Thanks for the note; I updated the link.
