### ISSUE TITLE
What is the lnExpect?

### ISSUE THREAD

**Issue by jspaezp** [UWPR/Comet#29]
Hello!

I was looking at the .pin output and wanted to know what the lnExpect score is.
I cannot seem to find a place where it would be documented ...

Appreciating your help beforehand!

**Comment by jke000** [comment]
One of Comet's reported scores is the expectation value or E-value.  lnExpect is the natural log of that expectation value.  Does this answer your question or would you like additional information on the expectation value calculation?

**Comment by jspaezp** [comment]
Oh ok, that makes sense.
Just to be sure, it refers to the score described in "A Method for Assessing the Statistical Significance of Mass Spectrometry-Based Protein Identifications Using General Scoring Schemes" by David Fenyö and Ronald C. Beavis
https://pubs.acs.org/doi/10.1021/ac0258709

Right?

(would you be interested in an improvement on the documentation of the .pin output to include references to the features?)

Thank you very much!
Best,
Sebastian

**Comment by jke000** [comment]
That reference is the first to present expectation values in conjunction with mass spectrometry analysis.  It's unlikely that I'll be adding references to the various feature in the file but I did just add brief descriptions of what each column represents in the .pin output [here](https://uwpr.github.io/Comet/parameters/parameters_202201/output_percolatorfile.html).
