### ISSUE TITLE
pep.xml search scores differ from pin file search scores

### ISSUE THREAD

**Issue by jonasscheid** [UWPR/Comet#34]
Hi! Thanks for the super quick fix last time!
Would it be possible to provide the same search scores in the pep.xml compared to the pin file?

pep.xml:

> <search_hit hit_rank="1" peptide="PRPVSKSIWPH" peptide_prev_aa="L" peptide_next_aa="R" protein="DECOY_sp|O43781|DYRK3_HUMAN" num_tot_proteins="1" num_matched_ions="5" tot_num_ions="40" calc_neutral_pep_mass="1302.719690" massdiff="0.004727" num_tol_term="0" num_missed_cleavages="0" num_matched_peptides="14634">
    <search_score name="xcorr" value="0.805"/>
    <search_score name="deltacn" value="0.034"/>
    <search_score name="spscore" value="18.8"/> 
    <search_score name="sprank" value="3"/>
    <search_score name="expect" value="2.88E+00"/>

pin file headers:

> SpecId	Label	ScanNr	ExpMass	CalcMass	lnrSp	deltLCn	deltCn	lnExpect	Xcorr	Sp	IonFrac	Mass	PepLen	Charge1	Charge2	Charge3	Charge4	Charge5	enzN	enzC	enzInt	lnNumSP	dM	absdM	Peptide	Proteins

Most of them one could compute based on the metadata of the search hit I suppose, but some like charge, lnNumSP etc. would not be included. However, I think it would be great to have the same search scores in both output files.

**Comment by jke000** [comment]
I appreciate any/all feature requests so definitely ask about them, no matter how big or small.  However, in this case, I would _highly_ prefer that you derive those numbers/values from the existing pep.xml output as the vast majority of users/tools that consume pep.xml file won't use this extra information. 

"lnNumSP" is the natural log of the "num_matched_peptides" attribute value.  And the "Charge1" through "ChargeN" columns are all populated with "0" except for charge state column of the peptide which has a value of "1" for the precursor charge state, which you can get from the "assumed_charge" attribute value.  There are "N" charge columns where "N" is determined by the "max_precursor_charge" search parameter value that is reported with all search parameters near the head of the pep.xml file.

With that being said, feel free to email me offline (engj at uw.edu) with your use case, especially if deriving the missing scores is hard and you can make the case that some number of proteomics researchers would benefit from such a change.  I wouldn't change the default pep.xml format for all users but it's within the realm of possibility to make a hidden search parameter that you could invoke to export these other values as pep.xml search score elements.

**Comment by jonasscheid** [comment]
Hi! Thanks for the offer 🙏🏼  We were just debating on the openMS dev meeting what the best solution would here. Ideally, an additional parameter would be really beneficial in terms of consistency for the future, although I would guess that might require some work to implement 😁

**Comment by jke000** [comment]
OK, I'll make another release soon (if not this week then early next week) which addresses this issue by adding a parameter to control optionally exporting additional search scores in the pep.xml output.  The release will also address issue 35 to allow searching mzML/mzXML files that are missing their scan index.  Both will be easy to implement.

**Comment by jke000** [comment]
@jonasscheid, I need clarification on which of the pin columns would you like to see as additional search scores in the pep.xml output.  The bold/italics columns below are the ones that make sense to me to add but I don't know how you guys are going to use this output.  Will your downstream tool(s) need the precursor charge state to be presented as separate `Charge1` thru `ChargeN` score entries with 0/1 values when the precursor charge is already reported as the `assumed_charge` attribute?  Similarly, given the availability of the experimental and calculated peptide masses, would you still want the mass difference `dM` and absolute value of the mass difference `absdM` also exported?  Lastly, `peptide_prev_aa="-"` in pep.xml is equivalent to `enzN` set to `1` and `peptide_next_aa="-"` is equivalent to `enzC` set to `1`; report enzN and enzC as search scores still given this?  Peptide length?

"SpecId Label ScanNr ExpMass CalcMass **_lnrSp_** **_deltLCn_** deltCn **_lnExpect_** Xcorr Sp **_IonFrac_** Mass PepLen Charge1 Charge2 Charge3 Charge4 Charge5 enzN enzC enzInt **_lnNumSP_** dM absdM Peptide Proteins"

**Comment by jonasscheid** [comment]
The features you highlighted bold would be great to have in there! That's it!
Thanks a lot🙏🏼

**Comment by jke000** [comment]
Completed with commit 7c9150d; will be in Comet release 2023.01.2.
