### ISSUE TITLE
The .exe file does not open 

### ISSUE THREAD

**Issue by ZappierFour50** [UWPR/Comet#36]
hi there, i was trying to compare my proteins to a database, this seemed to be the best option but the .exe file doesn't run and the read me is trying to get me to open a .sln file, which i can't seem to find. What is the issue? how do i resolve this?

**Comment by jke000** [comment]
Hi.  I just tested it and the exe does run as intended.   Here's the third paragraph on the Comet website:

_Comet is multithreaded, supports multiple input and output formats, and binaries are available for both Windows and Linux operating systems. Note that Comet is just a single command line binary that performs MS/MS database search. It takes in spectra in various supported input formats, using the [MSToolkit C++ library](https://github.com/mhoopmann/mstoolkit), and writes .pep.xml, .pin, .sqt and/or .txt files. You will need some other support tool(s) to actually make use of Comet results. Consider using [one of the many proteomics software suites](https://uwpr.github.io/Comet/releases/) that Comet is integrated into._

Given that it's a command line binary, it's not something you can double-click on and hope that a graphical interface pops up.  I'd advise you go choose one of the software suites listed in the link above; go give PatternLab a shot if you don't have experience with any of the software suites to know how to choose one over the others.

In the README.md that references the .sln file, it states that those are instructions on how to compile Comet in Visual Studio.  Assuming you're not a developer interesting in compiling the program yourself from source code, attempting to follow those instructions don't make sense.  With that, I'm going to close out this issue.  Go ahead and run Comet within PatternLab or SearchGUI and feel free to follow-up here (or ideally on the [Comet support forum](https://groups.google.com/g/comet-ms)) if you have further questions.  Good luck.
