### ISSUE TITLE
mzID output contains multiple SpectrumIdentificationResult tags for the same spectrum 

### ISSUE THREAD

**Issue by 524D** [UWPR/Comet#45]
Hi,

When mzIdentML (mzID) output is selected, and Comet finds multiple identifications for the same spectrum, each identification is reported in a separate `SpectrumIdentificationResult` tag. This is seems not correct according to [the mzID schema](https://github.com/HUPO-PSI/mzIdentML/blob/ab983643cb1dbaccf7ca85abcff139ab56364198/schema/mzIdentML1.1.1.xsd#L818C10-L818C10). 
In the Comet output, each result is enclosed in both a `SpectrumIdentificationResult` and a `SpectrumIdentificationItem` tag. Identifications belonging to the same spectrum should however be grouped under the same `SpectrumIdentificationResult`.

This problem prevents Comet mzID files to be read by [readMzIdData](https://lgatto.github.io/MSnbase/reference/readMzIdData.html) in R.

For completeness, there is [another problem](https://github.com/lgatto/MSnbase/issues/596) that prevents reading Comet output with readMzIdData, but that seems to be on the reader side.

I'm using Comet v2023.01.2

Best, Rob

**Comment by jke000** [comment]
Bob,

Thanks for reporting the issue.  I'm never confident I'm writing valid mzIdentML files even if they pass the validator.  I hopefully addressed both of these issues (`SpectrumIdentificationResult` and the "other" problem) with commits [5f6af8e](https://github.com/UWPR/Comet/commit/5f6af8e615de746c5181fac3125b727f92b3f901) and [f4e0c37](https://github.com/UWPR/Comet/commit/f4e0c3762d9cae30ddae8de04dfe9d1579eedc09).  For the "other" problem preventing reads by readMzIdData, I just got rid of that cvParam entry that doesn't seem useful and hopefully isn't required.

If you're willing to test the fix and need a compiled binary, let me know what OS you're using and I can compile a binary for you if helpful.

Jimmy

**Comment by 524D** [comment]
Hi Jimmy,

Thanks for your very quick reply. Of course it would be great if you could send me a test version, either Windows or Linux is fine. However, I can probably only test by October 24 since I'm not at work until then.

Best, Rob

**Comment by jke000** [comment]
Rob, you can find a Linux binary at `http://proteomicsresource.washington.edu/dist/comet.2023020.linux.exe`

**Comment by 524D** [comment]
Hi Jimmy,

The mzID output look good with the new version and also works perfectly with readMzIdData. Many thanks for the quick fix.

Rob
