### ISSUE TITLE
N-term enzyme miss-cleavage

### ISSUE THREAD

**Issue by cpaul32015** [UWPR/Comet#47]

**Comment by cpaul32015** [comment]
In another case where it seems more like a bug is where I searched with a custom enzyme lysarginase which cleaves N-term to 'K' and 'R', even when I set the allowed MC to 3 I am actually getting peptides up to 5 MC (counting K and R as miss-cleaved sites). Could this issue be something to do with how the algorithm treats proteases cleaves on the N-term to the AA? 

![20240106_lysarginaseMC_To_CometGitHub](https://github.com/UWPR/Comet/assets/54745839/955c65b7-1f5d-494a-9a56-3bed6f7a49b4)

**Comment by jke000** [comment]
Thanks for reporting this.  I just spent about 30 minutes looking into this and there is a bug with the logic of counting missed cleavages; at first glance appears to be an issue with N-term enzymes/cleavages.  I'll spend time on Monday addressing this and comment more at that time.

**Comment by cpaul32015** [comment]
Thank you for the quick response over the weekend! I want to correct about my initial question, turned out I mistakenly counted the cleavage site of AspN to be before 'N' but it should be before 'D', I got that corrected and the MCs for that search made sense now.
The custom lysarginase is still reporting results with 5 MCs when I set to use 3 MCs in the parameter file, it will be great if you can look into it further if it is indeed a bug.

Have a great weekend!

**Comment by jke000** [comment]
Zixiang, I implemented the little fix for this issue but I want to do a few additional tests just to confirm all is well.  If you're able to test on your lysarginase dataset, I have [patched Comet binaries here](http://proteomicsresource.washington.edu/dist/20240108_comet_patch/) that you can download.  It would be reassuring to hear that this addresses the issue in your dataset.

**Comment by cpaul32015** [comment]
Hi Jimmy,

Thanks for so quickly addressing the issue, is the current state of Comet search affecting the counting of all N-term enzymes or just the custom ones? From my previous tests it appears that AspN in combination with trypsin worked correctly but the custom lysarginase was having issue. I normally run Comet through a internal platform so I will need to consult with our computational team to see what is the best way for me to test the fix.

**Comment by jke000** [comment]
The bug affected properly counting all N-term enzyme missed cleavages.

**Comment by jke000** [comment]
I'm going to close this issue which is addressed with commit [d7f202b](https://github.com/UWPR/Comet/commit/d7f202b7b91ec64b8f9fac5b987ba2eae640cfb5) and will be included in the next release, whenever that might be.
