### ISSUE TITLE
Question: Met-loss and Met-loss+Acetyl modifications

### ISSUE THREAD

**Issue by JannikSchneider12** [UWPR/Comet#51]
Hello everyone,

I have a problem when I try to include these two variable modifications. So I want to include these:
![image](https://github.com/UWPR/Comet/assets/72038436/d7a4bf81-0f5b-4902-8d52-e17a5bd6f7a8)

And this is my approach:
variable_mod03 = -131.040485 n 0 3 0 0 0 0.0		# Met-loss on residue M of protein's N-terminus
variable_mod04 = -89.029920 n 0 3 0 0 0 0.0		# Met-loss + Acetyl on residue M of protein's N-terminus

I also tried it with "nM" instead but I still get a segmentation fault, when I try to run comet. Does somebody know whats wrong?

Thanks for your time and help

**Comment by jke000** [comment]
The big negative n-term mod masses are the issue.  With the large negative variable modification mass on the n-terminus, a peptide that begins with a glycine or alanine or serine are going to have a negative b1-ion mass which is causing the segmentation fault. 

I could be wrong but think that what you're trying to accomplish would be correctly specified by a combination of the following two parameters.  The first allows for the consideration of removing the start methionine residue in a  protein sequence (aka Met-loss).  And the second parameter below specifies acetylation of the protein N-terminus.  When those two happen in tandem, you effectively get Met-loss + Acetyl.
- [clip_nterm_methionine](https://uwpr.github.io/Comet/parameters/parameters_202301/clip_nterm_methionine.html) = 1
- variable_mod03 = 42.010565 n 0 1 0 0 0 0.0

**Comment by JannikSchneider12** [comment]
Hey, 

Thank you very much for your help. Now it works without the segmentation fault. However I find it a bit suspicious that I don't see explicitly any cases where Met-loss or Met-loss+Acetyl occurs in my output. But I have cases with "n[42.0106]" , so with Acetyl at the terminus. Does the clip_nterm_methionine parameter appears in a different format in the resulting peptide sequence?

Thanks again for your time and help

**Comment by jke000** [comment]
he "clip_nterm_methionine" will remove start methionine residues and will also consider the next amino acid the protein N-terminus (that can now be acetylated).  Currently, the only way to tell if there is a Met-loss or Met-loss+Acetyl is to see if the previous amino acid is a methione residue.

**Comment by JannikSchneider12** [comment]
So in cases where there is a met-loss, the M in the peptide sequence is still be present? Or what do you mean with previous amino acid? So I am not sure to what I have to check against

**Comment by jke000** [comment]
Comet reports the amino acid residues before and after the identified peptide.  So you would look at the previous or preceding amino acid residue and see if it's an `M`, which would indicate the start methionine was removed (aka your Met loss).  If the preceding residue is listed as a dash (`-`), it means there's no preceding residue so the first residue in the identified peptide is the N-terminal residue of the protein.  In the text output, there's a column `modified peptide` where the peptides are reported as `R.HMRLHEEEK.F` where the flanking amino acids to the identified `HMRLHEEEK` peptide are `R` and `F`, respectively.  There are also columns `prev_aa` and `next_aa` where the `prev_aa` would be `R` and the `next_aa` after the identified peptide in the protein sequence is an `F`.  This convention of listing the previous/next flanking amino acids is also used in the Percolator pin output under the `Peptide` columns.  For the pep.xml output, there's an attribute named `peptide_prev_aa` in the `search_hit` element that lists the previous/preceding amino acid.  You're looking for an `M` for the previous amino acid for the Met-loss (which I'm now really hoping you find a few!).

**Comment by JannikSchneider12** [comment]
Sorry for asking that much but I actually don‘t get it 100% why an M as preceding amino acid would indicate me a met-loss. So those flagging amino acids are the amino acids of the protein before and after the identified peptide. But not the first and last amino acids of the identified peptide itself right? So how do I know that there was originally an M present and now not any more based on the „peptide_seq“ of my percolator xml ?

**Comment by jke000** [comment]
It's possible I don't understand what you're looking for but let me try with this example:

ProteinA sequence:  `MVNSVVFRWDITVDGKPLGRIS...`

The first tryptic peptide in ProteinA is `MVNSVVFR`.  If this peptide were identified and reported, the previous amino acid would be `-` to reflect this is the N-terminus of the protein so there is no previous amino acid.  And the next/following amino acid would be `W`.

With the `clip_nterm_methionine` parameter in Comet, the search would also consider this protein sequence with the N-terminal methionine removed (what I'm assuming is the Met-loss you're looking for).  If this occurred, the identified peptide would be `VNSVVFR` with the previous amino acid `M` and the next amino acid `W`.  This removal/loss of the N-terminal methionine is the only way you would be able to identify `VNSVVFR` as the N-terminus of this peptide wouldn't by a tryptic cleavage site.  So any peptide with a previous amino acid of an `M` would reflect such a methionine loss as a proper tryptic cleavage could only have a `K`, `R` or `-` as the previous amino acid.  This all goes out the window if you're performing something like a semi-tryptic search.

Let me know if this makes it any clearer.  Or are you looking for some other functionality?

**Comment by JannikSchneider12** [comment]
Thanks again for the explanations. I didn't got the mechanism that in case of an Met-loss the originally M as the first element of the peptide sequence now becomes the prev_aa. That was the point that I missed. I thought the prev_aa was not affected in case the M is removed, but now I understand.

Thanks again for your time and help
