### ISSUE TITLE
Issue with building Comet from solution file (expat.h)

### ISSUE THREAD

**Issue by dan-cam-4064** [UWPR/Comet#57]
Thank you for your help with the last issue I had. I have now been able to clone the repo and build from within VS2019. 

It is throwing the error 16 times that that it cannot open the file "expat.h". The code is C1083 and the message is "cannot open file 'expat.h': No such file or directory", within the mzParser.h file, at line 32. 

It was throwing a similar error with zconf.h but I manually downlaoded and copied this into the correct folder. When I tried to copy in expat.h, it is already in the correct folder but it does not seem to recognise that it is there. I wanted to know if this had been seen and whether you could please help me with this. 

Many thanks,
dan-cam

**Comment by jke000** [comment]
In the README.md file, which you can also see at [the bottom of Comet's GitHub page](https://github.com/UWPR/Comet), it lists out the simple steps you need to take to compile Comet.exe using Microsoft's Visual Studio.  If you missed the README, go back and take a look at it.  I'm guessing you did not set the build targets to "Release" and "x64" before attempting to compile.  If that missing step isn't the problem then I would need access to your system to figure out what's wrong.

**Comment by jke000** [comment]
As its been over a week, I'll close this issue with the assumption that this issue has been addressed. If not, feel free to follow-up at any time.
