### ISSUE TITLE
Peptide Mass Tolerances are inverted?

### ISSUE THREAD

**Issue by cbielow** [UWPR/Comet#59]
I was debugging Comet v2024.01.0, and found that the new mass tolerance parameters are probably buggy.
e.g.
using
```
peptide_mass_tolerance_upper = 0.0    # upper bound of the precursor mass tolerance
peptide_mass_tolerance_lower = -20.0   # lower bound of the precursor mass tolerance; USUALLY NEGATIVE TO BE LOWER THAN 0
```
in the param.txt causes 
```
g_staticParams.tolerances.dInputToleranceMinus == -0
g_staticParams.tolerances.dInputTolerancePlus == 20
```
see https://github.com/UWPR/Comet/blob/v2024.01.0/CometSearch/CometSearchManager.cpp#L745

And thus in the results something like this:

```
precursor_neutral_mass="1107.516847" ...
calc_neutral_pep_mass="1107.528201" massdiff="-0.011354" ...
```
i.e. the matched peptide is heavier than the measured precursor mass, even though I specified `peptide_mass_tolerance_upper = 0.0`

So unless I'm getting the semantics wrong here, this needs a fix (which is easy to do, but I just wanted to make sure the problem is real).

**Comment by jke000** [comment]
The application of the tolerances is correct and I added a bit more text to the [peptide_mass_tolerance_upper](https://uwpr.github.io/Comet/parameters/parameters_202401/peptide_mass_tolerance_upper.html) and [peptide_mass_tolerance_lower](https://uwpr.github.io/Comet/parameters/parameters_202401/peptide_mass_tolerance_lower.html) parameter pages to hopefully clarify them.

I think the confusion is just semantics or reference.  The mass error or massdiff is defined as (experimental - theoretical).  And these tolerance bounds are effectively the bounds on this allowed mass error.  So using when you specify `peptide_mass_tolerance_upper = 0.0` and `peptide_mass_tolerance_lower = -20.0`, this means that the identified, theoretical peptide masses can be up to 20 units larger than the experimental mass, resulting in a massdiff up to -20 units (be it ppm or daltons).  So the matched peptides are expected to be heavier than the measured mass in this context.  fwiw, these two parameters are consistent with how MSFragger applies them.
