### ISSUE TITLE
Time of peptide ID in mzid

### ISSUE THREAD

**Issue by julianu** [UWPR/Comet#65]
This is a very minor but:
right now you export the time of the `<SpectrumIdentificationResult>` in mzid with the CVParam "retention time" (MS:1000894). The mzid-documentation recommends the usage of "scan start time" (MS:1000016), though.
It's maybe not intuitive, but should be used like that.

Just wanted to mention it, as I stumbled across it :)

**Comment by jke000** [comment]
Thanks Julian.  I appreciate all feedback, good or bad, so keep these coming if you find any more!  It's clear I know very little about the mzid format so I used the supplied mzid example files as templates when generating Comet's mzid output.  I believe I simply copied the "retention time" param use from [this mzIdentML v1.2 example file](https://github.com/HUPO-PSI/mzIdentML/tree/master/examples/1_2examples/PeptideShaker_mzid_1_2_example).  I do now see on page 73 of the 1.2 release doc that it shows MS:1000016 as an example child term of Spectrum Identification Result.  I just made this quick change with commit 091e269.  I plan on making a maintenance release later today or tomorrow which will include these mzid corrections as well address the other bugs that have been reported with the most recent release.
