### ISSUE TITLE
[Feature request] Alternative protein separator

### ISSUE THREAD

**Issue by jspaezp** [UWPR/Comet#66]
Hello there!

I was wondering if you would consider viable a config option to change the separator of the proteins field. Right now it separates the last protein column with tabs `Prot1\tProt2`, which breaks many tools that expect a consistent number of tabs per line (pandas, polars, duckdb ...) or silently drops the non-first.

What I am suggesting is a `protein_column_separator` config option that defaults to "\t", but could be assigned to something like ":::", where your protein column would end up with fields like so `Prot1:::Prot2`.

Let me know what you think!
-Kindest wishes-Sebastian

**Comment by jke000** [comment]
Yes, I'll add in that parameter to allow the user to specify the delimiter in the Percolator pin output.  I would not have chosen that same protein delimiter when the rest of the file also uses a tab [but that's how it's expected in the Percolator pin tsv format](https://github.com/percolator/percolator/wiki/Interface).  I'm going to close this issue with this comment but am confirming that I will add in this parameter within the hour and in the 2024.01.1 maintenance release that I also hope to push out today.

**Comment by jspaezp** [comment]
Thanks Jimmy! You rock!

**Comment by jke000** [comment]
I just created the 2024.01 rev. 1 release.  I named the new parameter [pinfile_protein_delimiter](https://uwpr.github.io/Comet/parameters/parameters_202401/pinfile_protein_delimiter.html) which allows you to change the Percolator pin file protein field delimiter to some other character or string.

**Comment by gessulat** [comment]
Wow, this is amazing. Thank you for this super quick response!
