### ISSUE TITLE
inconformity in documentation and parameter file for fragindex_skipreadprecursors

### ISSUE THREAD

**Issue by MaLLLiYA** [UWPR/Comet#69]
The meaning of the valid values ​​seems inconsistent.

In the online documentation for parameter fragindex_skipreadprecursors:

> Valid values are 0 or 1.
> 0 = skip reading precursors from the input ifle
> 1 = read precursors from the input file

In the comet.params.new file generated by the command `comet -q` :

> fragindex_skipreadprecursors = 0       # 0=read precursors to limit fragment ion index, 1=skip reading precursors

**Comment by jke000** [comment]
Hi, thanks for noticing and reporting this issue.  The online documentation was wrong and [has been corrected on the website](https://uwpr.github.io/Comet/parameters/parameters_202402/fragindex_skipreadprecursors.html).  The correct values for that parameter are:
- 0 = read precursors from the input file (aka do not skip)
- 1 = skip reading precursors from the input file
