### ISSUE TITLE
Comet-PTM documentation

### ISSUE THREAD

**Issue by tryhard124** [UWPR/Comet#70]
I looked through the documentation for all github releases and found no mention of Comet-PTM integration. I saw that these efforts were still active in 2021 and I see an open issue regarding PTM scores. Could I be directed to the documention on how to use it?

**Comment by jke000** [comment]
You can [find Comet-PTM here](https://github.com/CNIC-Proteomics/Comet-PTM).  There was effort to integrate that code into this Comet repository but that was never completed.  So you're going to have to use Comet-PTM from the linked repository as no such functionality exists in this Comet repository.

Issue #68 about adding a modification localization score to Comet's output is unrelated to Comet-PTM.
